---
caddy_dashboard_name: homeserver.lan

caddy_sites:
  - name: pve.homeserver.lan
    title: Proxmox
    icon: fas fa-server
    upstream: https://192.168.1.50:8006
    upstream_tls_insecure: true
  - name: pihole.homeserver.lan
    title: Pi-hole
    icon: fas fa-shield-halved
    upstream: http://192.168.1.60:80
  - name: homeassistant.homeserver.lan
    title: Home Assistant
    icon: fas fa-house
    upstream: http://192.168.1.62:80
