---
pihole_web_domain: pihole.homeserver.lan

pihole_local_dns_records:
  - name: homeserver.lan
    ip: 192.168.1.64
  - name: pve.homeserver.lan
    ip: 192.168.1.64
  - name: pihole.homeserver.lan
    ip: 192.168.1.64
  - name: status.homeserver.lan
    ip: 192.168.1.64
  - name: jellyfin.homeserver.lan
    ip: 192.168.1.64
  - name: torrent.homeserver.lan
    ip: 192.168.1.64
  - name: prowlarr.homeserver.lan
    ip: 192.168.1.64
